name: Terraform workflow

on: workflow_dispatch

permissions:
  id-token: write    # Required for OIDC login
  contents: read     # Enough to checkout repository code

jobs:
  my_first_job:
    name: first job
    runs-on: [self-hosted, anjali]
    steps:
    - name: jaa login kr Azure se 
      uses: Azure/login@v2.3.0
      with:   
          client-id: 797b2efe-6a48-4c3b-b1b1-71b08221e046
          tenant-id: ee2f7139-4072-4385-99fc-82bd6f563aa6
          subscription-id: 98b7163f-e961-4b65-98c2-7a6dc2edf5b7

    - name: copy kr repo to self hosted runner me
      uses: actions/checkout@v4
      
    - name: Terraform Init chala
      id: init
      run: terraform init -input=false
      working-directory: ./parent_module    

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true
      working-directory: ./parent_module 
     
