name: Terraform workflow

on: workflow_dispatch

# permissions:
#   id-token: write    # Required for OIDC login
#   contents: read     # Enough to checkout repository code

jobs:
  my_first_job:
    name: first job
    runs-on: [self-hosted, anjali]
    steps:
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:   
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       
     
    # - name: Azure CLI Login
    #   uses: azure/login@v2
    #   with:
    #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    

    # az login
    # terraform install
    # terraform init
    # terraform plan
    # terraform apply
  
